# Generated by Django 2.2.7 on 2019-11-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldado',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
    ]
